### ISSUE TITLE
电影的二级分类是不是不支持origin_country？

### ISSUE THREAD

**Issue by lxj12328** [jxxghp/nas-tools#1775]
## 你使用的 NASTool 是什么版本，什么环境？

> NASTool 版本: 
>v2.2.3 5f9cadcb
> 环境: 
>debian docker

## 你遇到什么问题了？

> default-category.yaml 中 movie 配置了origin_country参数，发现这个配置不生效。配置文件如下：
```
# 配置电影的分类策略， 配置为空或者不配置该项则不启用电影分类
movie:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  国产电影:
    # 分类依据，可以是：original_language 语种、origin_country 国家或地区、genre_ids 内容类型等，只要TMDB API返回的字段中有就行
    # 配置多项条件时，需要同时满足；不需要的匹配项可以删掉或者配置为空
    # 匹配值对应用,号分隔，这里是匹配语种
    origin_country: 'CN'
  港台电影:
    origin_country: 'TW,HK,MO'
  欧美电影:
    origin_country: 'AR,AU,BE,BR,CA,CH,CL,CO,CZ,DE,DK,EG,ES,FR,GR,IQ,IR,IT,MX,NL,NO,PH,PK,PL,SE,TR,US,GB,NZ,SA,PT'
  日韩电影:
    origin_country: 'JP,KP,KR,SG'
  待整理:
```

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> movie 能否也支持origin_country选项？

## 给出程序界面截图、后台运行日志或配置文件

> 
![CleanShot 2022-10-25 at 13 46 07](https://user-images.githubusercontent.com/16728544/197692624-21c859f6-2981-4bc2-8619-670041d9fb2a.png)

**Comment by Shurelol** [comment]
建议用语种分类

**Comment by lxj12328** [comment]
> 建议用语种分类

语种不好区分大陆电影和港台电影。

**Comment by Shurelol** [comment]
已修复，等后面更新吧

**Comment by lxj12328** [comment]
今天升级了v2.3.0 7e44d0af版本后测试发现出来的结果还是是有问题。下面是配置文件：
```
# 配置电影的分类策略， 配置为空或者不配置该项则不启用电影分类
movie:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  国产电影:
    # 分类依据，可以是：original_language 语种、production_countries(电影)/origin_country(dianshiju) 国家或地区、genre_ids 内容类型等，只要TMDB API返回的字段中有就行
    # 配置多项条件时，需要同时满足；不需要的匹配项可以删掉或者配置为空
    # 匹配值对应用,号分隔，这里是匹配语种
    production_countries: 'CN'
  港台电影:
    # 匹配 genre_ids 内容类型，16是动漫
    production_countries: 'TW,HK,MO'
  # 未配置任何过滤条件时，则按先后顺序不符合上面分类的都会在这个分类下，建议配置在最末尾
  欧美电影:
    production_countries: 'AR,AU,BE,BR,CA,CH,CL,CO,CZ,DE,DK,EG,ES,FR,GR,IQ,IR,IT,MX,NL,NO,PH,PK,PL,SE,TR,US,GB,NZ,SA,PT'
  日韩电影:
    production_countries: 'JP,KP,KR,SG'
  东南亚电影:
    production_countries: 'TR,TH,MM,MY,VN,IN'
```
下面是测试的结果图片：
国产电影结果：
![CleanShot 2022-10-28 at 10 57 53](https://user-images.githubusercontent.com/16728544/198485025-67f795b4-59b8-4209-939b-94e2178cd835.png)
港台电影结果：
![CleanShot 2022-10-28 at 11 00 09](https://user-images.githubusercontent.com/16728544/198486166-6c7ae6ca-7a7f-4fa5-bc96-68f2d31ae56e.png)
![CleanShot 2022-10-28 at 11 03 20](https://user-images.githubusercontent.com/16728544/198487906-e8cc341f-2039-4e99-82a5-229251aee76f.png)

**Comment by Shurelol** [comment]
二级分类配置文件修改后需要重启
![image](https://user-images.githubusercontent.com/16237201/198493523-890cfafa-8ba6-4a45-80f3-54ece41a84e2.png)
![image](https://user-images.githubusercontent.com/16237201/198493677-2494a697-ea04-421c-ad92-0eab8ca4d45f.png)
![image](https://user-images.githubusercontent.com/16237201/198497010-5778091a-7947-4877-92fc-1ea8070a7a51.png)

**Comment by lxj12328** [comment]
> 二级分类配置文件修改后需要重启 ![image](https://user-images.githubusercontent.com/16237201/198493523-890cfafa-8ba6-4a45-80f3-54ece41a84e2.png) ![image](https://user-images.githubusercontent.com/16237201/198493677-2494a697-ea04-421c-ad92-0eab8ca4d45f.png) ![image](https://user-images.githubusercontent.com/16237201/198497010-5778091a-7947-4877-92fc-1ea8070a7a51.png) ![image](https://user-images.githubusercontent.com/16237201/198497071-c9fa3f65-0db3-442f-8b36-7c36c9a78828.png)

好了，谢谢大佬！

**Comment by Xm798** [comment]
@lxj12328 请问按照你的分类方式，`健听女孩 (2021)` 能否正常被识别呢？

我这边被放到未分类了

<img width="700" alt="image" src="https://user-images.githubusercontent.com/48074861/203901969-a2b5928e-98fb-4419-b231-7b79d266be35.png">

<img width="376" alt="image" src="https://user-images.githubusercontent.com/48074861/203901987-65e4d7bf-3f80-4782-8641-b8e2f96b5975.png">


```yaml
movie:
  动画电影:
    genre_ids: '16'
  华语电影:
    original_language: 'zh,cn,bo,za'
  韩国电影:
    original_language: 'ko'
  东南亚电影:
    production_countries: 'TR,TH,PH,MM,MY,VN,IN'
  日本电影:
    original_language: 'ja'
  欧美电影:
    production_countries: 'AR,AU,BE,BR,CA,CH,CL,CO,CZ,DE,DK,EG,ES,FR,GR,IQ,IR,IT,MX,NL,NO,PK,PL,SE,TR,US,GB,NZ,SA,PT'
  儿童电影:
    genre_ids: '10762'
  未分类电影:
```
