### ISSUE TITLE
[Errno 18] Cross-device link 硬链接失败，错误码 -1

### ISSUE THREAD

**Issue by believerd** [jxxghp/nas-tools#3214]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: v2.8.2
>
> 环境: docker
>

## 你遇到什么问题了？

> 硬链接失败，错误码 -1 ，目录已按wiki设置为共同的上级目录。

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？

> 是

## 你期望的结果

> 描述以下你期望的结果

## 给出程序界面截图、后台运行日志或配置文件
`[Errno 18] Cross-device link: '/Media/downloads/xxxx (xxx) [1080p]/xxx.mp4' -> '/Media/movies/xxxx (xxx) [1080p]/xxx.mp4'`
### docker目录映射
`- /Media:/Media`
`/Media 目录下 有 downloads movies 文件夹，/Media 为共同的上级目录`

### docker logs
```
Callstack:
Traceback (most recent call last):
  File "/nas-tools/app/utils/system_utils.py", line 167, in link
    os.link(os.path.normpath(src), os.path.normpath(dest))
```
### 下载目录
```
downloaddir:
- save_path: /Media/downloads
  type: ''
  category: ''
  container_path: /Media/downloads
  label: ''
```
> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志
