### ISSUE TITLE
请问docker-compose启动，如何访问或者指定宿主机磁盘路径

### ISSUE THREAD

**Issue by ookinasiawase** [jxxghp/nas-tools#3445]
## Q：docker启动不知道如何访问宿主机磁盘路径，找不到盘符

How does the dock container access the host file directory

### 运行环境

ubuntu 22.04 + docker.io + docker-compose2.2.3

MacOS13 + docker desktop 

```bash
sg@iMac nastools % docker -v
Docker version 20.10.22, build 3a2c30b
Docker Compose version v2.15.1
```

---

## 磁盘

系统盘ssd + 3TB机械

## docker-compose 启动如下

官方的模板，几乎没动

```yaml
version: "3"
services:
  nas-tools:
    image: jxxghp/nas-tools:latest
    ports:
      - 3000:3000        # 默认的webui控制端口
    volumes:
      - ./config:/config   # 冒号左边请修改为你想保存配置的路径
      - /Volumes/3T/vedio:/vedio   # 媒体目录，多个目录需要分别映射进来，需要满足配置文件说明中的要求
    environment: 
      - PUID=0    # 想切换为哪个用户来运行程序，该用户的uid
      - PGID=0    # 想切换为哪个用户来运行程序，该用户的gid
      - UMASK=000 # 掩码权限，默认000，可以考虑设置为022
      - NASTOOL_AUTO_UPDATE=false  # 如需在启动容器时自动升级程程序请设置为true
      - NASTOOL_CN_UPDATE=false # 如果开启了容器启动自动升级程序，并且网络不太友好时，可以设置为true，会使用国内源进行软件更新
     #- REPO_URL=https://ghproxy.com/https://github.com/jxxghp/nas-tools.git  # 当你访问github网络很差时，可以考虑解释本行注释
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
    privileged: true
```

## 报错

加载路径失败: [Errno 2] No such file or directory: ''

## jellyfin & qbittorrent 等也是同样的问题。

# 求解答，万分感谢。
