### ISSUE TITLE
关于使用自定义二级分类而产生的问题

### ISSUE THREAD

**Issue by chingxuds** [jxxghp/nas-tools#378]
我依据`default-category.yaml`创建了自定义的`custom-category.yaml`，文件及内容如下：

<img width="387" alt="custom-category.yaml" src="https://user-images.githubusercontent.com/3142486/175816231-00676bf6-22c8-43db-96d3-16ea67242d4c.png">

```yaml
# 配置电影的分类策略， 配置为空或者不配置该项则不启用电影分类
movie:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  国产电影:
    # 分类依据，可以是：original_language 语种、origin_country 国家或地区、genre_ids 内容类型等，只要TMDB API返回的字段中有就行
    # 配置多项条件时，需要同时满足；不需要的匹配项可以删掉或者配置为空
    # 匹配值对应用,号分隔，这里是匹配语种
    #original_language: 'zh,cn,bo,za'
    origin_country: 'CN,TW,HK'
  # 未配置任何过滤条件时，则按先后顺序不符合上面分类的都会在这个分类下，建议配置在最末尾
  国外电影:

# 配置电视剧的分类策略， 配置为空或者不配置该项则不启用电视剧分类
tv:
  # 分类名同时也是目录名，会按先后顺序匹配，匹配后程序会按这个名称建立二级目录
  # 如果有配置动漫独立目录，则实际上不会使用到tv下的动漫二级分类
  动画:
    # 匹配 genre_ids 内容类型，16是动漫
    genre_ids: '16'
  纪录片:
     # 匹配 genre_ids 内容类型，99是纪录片
    genre_ids: '99'
  儿童:
    # 匹配 genre_ids 内容类型，10762是儿童
    genre_ids: '10762'
  综艺:
    # 匹配 genre_ids 内容类型，10764 10767都是综艺
    genre_ids: '10764,10767'
  国产剧:
    # 匹配 origin_country 国家，CN是中国大陆，TW是中国台湾，HK是中国香港
    origin_country: 'CN,TW,HK'
  欧美剧:
    # 匹配 origin_country 国家，主要欧美国家列表
    origin_country: 'US,FR,GB,DE,ES,IT,NL,PT,RU,UK'
  日韩剧:
    # 匹配 origin_country 国家，主要亚洲国家列表
    origin_country: 'JP,KP,KR,TH,IN,SG'
  # 未匹配以上分类，则命名为其他
  其他节目:
```

然后发现了两个问题：
问题1：国产电影分类不生效，电影全部被分类到国外电影。

<img width="543" alt="图片" src="https://user-images.githubusercontent.com/3142486/175816332-81bf27f8-716c-40d5-99ee-d5f043830c92.png">
<img width="539" alt="图片" src="https://user-images.githubusercontent.com/3142486/175816345-15c00278-de13-4a42-ac1c-490e99202030.png">
<img width="540" alt="图片" src="https://user-images.githubusercontent.com/3142486/175816583-ac079f87-cdc1-460d-9d3c-4315f630d8b5.png">

问题2：动画剧集没有被分类到动画，也没有放到【其他节目】中，而是放到了根目录下

<img width="496" alt="图片" src="https://user-images.githubusercontent.com/3142486/175816652-2ca0d73f-8fed-4ad0-97aa-be72cdcb3092.png">
