### ISSUE TITLE
启动成功后，程序创建数据库失败。

### ISSUE THREAD

**Issue by small-ora** [jxxghp/nas-tools#792]
如图,启动成功后,日志显示创建数据库失败,把配置文件和镜像删除后,重新拉取,重新启动也是同样的问题.
![Snipaste_2022-08-24_23-17-44](https://user-images.githubusercontent.com/33921583/186457574-be3c10a2-f028-42e8-9517-11909e143ee3.png)

docker-compose配置如下
```
nastools:
    image: jxxghp/nas-tools:latest
    ports:
      - 3000:3000
    volumes:
      - /mnt/nas/nastools/config:/config
      - /mnt/nas/qbittorrent/downloads:/share/download
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Shanghai
      - UMASK=000
      - NASTOOL_AUTO_UPDATE=false
      - REPO_URL=https://ghproxy.com/https://github.com/jxxghp/nas-tools.git
    restart: always
    network_mode: bridge
    hostname: nas-tools
    container_name: nas-tools
```
