### ISSUE TITLE
配置文件中的目录同步带@link

### ISSUE THREAD

**Issue by sungamma** [jxxghp/nas-tools#810]
![image](https://user-images.githubusercontent.com/33790/186838828-7086b2d1-3e34-496f-928f-7db081349256.png)
![image](https://user-images.githubusercontent.com/33790/186838949-22ca87b7-e64b-48a8-9ef4-11355bedff54.png)
而且之前手动转移的时候也出现了问题，手动转移的壮志凌云2转移到了links/电影/欧美电影/links/壮志凌云2目录下
有时候启动时，也出现不能识别带@link的目录

14:43:56 INFO - 配置文件地址：/config/config.yaml
14:43:56 INFO - NASTool 当前版本号：v2.0.2
14:43:56 INFO - 日志输出类型为：file
14:43:56 INFO - 日志将写入文件：/config/logs
14:43:56 INFO - WEB管理页面用户：sun
14:43:56 INFO - 未启用https，请使用 http://IP:3005 访问管理页面
14:43:56 INFO - TMDB匹配模式：正常模式
14:43:56 INFO - 媒体管理软件设置为：jellyfin
14:43:56 INFO - 电影分类：华语电影 外语电影
14:43:56 INFO - 电视剧分类：纪录片 儿童 综艺 国产剧 欧美剧 日韩剧 未分类
_**14:43:56 WARN - 目录不存在，该目录同步功能已关闭：/volume1/movie/QB@link**_
14:43:56 INFO - 目录同步转移模式为：硬链接
14:43:56 INFO - 下载软件设置为：qbittorrent
14:43:56 INFO - 下载文件转移模式为：硬链接
14:43:56 INFO - 索引器设置为：builtin
14:43:56 INFO - 微信等移动端渠道搜索已开启自动择优下载
14:43:56 INFO - 保种时间未配置，自动删种功能已关闭
14:43:56 INFO - 下载软件监控未开启，下载器监控功能已关闭
14:43:56 INFO - 开始启动进程...
14:43:57 INFO - 【RUN】站点自动签到服务时间范围随机模式启动，起始时间于19:01
14:43:57 INFO - 【RUN】RSS订阅服务启动...
14:43:57 INFO - 【RUN】订阅定时搜索服务启动...
14:43:57 INFO - 【RUN】豆瓣同步服务启动...
14:43:57 INFO - 【SYNC】读取到监控目录：/volume1/movie/QBTV，转移方式：硬链接
14:43:57 INFO - 【SYNC】读取到监控目录：/volume1/movie/QB，转移方式：硬链接
14:43:57 INFO - 【RUN】/volume1/movie/QBTV 的监控服务启动...
14:43:57 INFO - 【RUN】/volume1/movie/QB 的监控服务启动...

**Comment by sungamma** [comment]
关掉nas-tools，手动修改config.yml，开启nas-tools能够解决。不过这个如何产生这个错误就不知道了

**Comment by sungamma** [comment]
对比了config.yml，
最新的配置是这样的
```
# 【配置文件夹监控】：文件夹内容发生变化时自动识别转移
sync:
  # 【监控目录列表】：监控目录有文件变化时会自动进行转移处理
  # 可以配置多个，按'源目录|目的目录|未识别目录@转移模式'格式配置，源目录为需要同步的目录，目的目录为识别和改名后存放的目录，未识别目录为无法识别时转移的目录
  # 使用[]将整项括起来表示该目录配置不识别重命名，使用#将整项括起来表示该目录配置不启用
  # 目的目录和未识别目录为可选项；目的目录不配置时会自动分类往媒体库目录存放；未识别目录仅用于备份，程序也不会主动删除，可以不配置该目录，未识别的记录可会在媒体整理->手动识别找到并手工处理
  sync_path:
  # 【监控目录操作系统类型】：windows、linux。如果是windows，目录同步功能性能会比较差，会导致NAS不能休眠，除非是挂载的windows的远程共享目录或者是windows的docker，否则建议设置为linux
  nas_sys: linux
```

之前的配置是这样的

```
# 【配置文件夹监控】：文件夹内容发生变化时自动识别转移
sync:
  # 【监控目录列表】：监控目录有文件变化时会自动进行转移处理
  # 可以配置多个，按'源目录|目的目录|未识别目录@转移模式'格式配置，源目录为需要同步的目录，目的目录为识别和改名后存放的目录，未识别目录为无法识别时转移的目录
  # 使用[]将整项括起来表示该目录配置不识别重命名，使用#将整项括起来表示该目录配置不启用
  # 目的目录和未识别目录为可选项；目的目录不配置时会自动分类往媒体库目录存放；未识别目录仅用于备份，程序也不会主动删除，可以不配置该目录，未识别的记录可会在媒体整理->手动识别找到并手工处理
  sync_path:
  # 【监控目录操作系统类型】：windows、linux。如果是windows，目录同步功能性能会比较差，会导致NAS不能休眠，除非是挂载的windows的远程共享目录或者是windows的docker，否则建议设置为linux
  nas_sys: linux
```
新的设置的可以带@link，但是程序呢又识别不了。应该还是有点问题的
